name: âš¡ï¸ Update Status. âš¡ï¸
on:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Set up Python 3.9 ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ğŸŒ€ Clone The Repo ğŸŒ€
        uses: actions/checkout@W
        with:
          repository: ${{ secrets.REPO_NAME }}
      - name: ğŸ“€ Install Dependencies. ğŸ“€
        run: |
          pip install python-decouple tgcrypto pyrogram heroku3
          pip install --upgrade pip
      - name: ğŸƒâ€â™‚ï¸ Run The Bot. ğŸƒâ€â™‚ï¸
        run: |
          python3 main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ID: ${{ secrets.ID }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
